version: '3'

services:

  db:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./database/product_init.sql:/docker-entrypoint-initdb.d/product_init.sql
      - ./database/orders_init.sql:/docker-entrypoint-initdb.d/orders_init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 30s
      timeout: 15s
      retries: 5
      
  gateway:
    build: ./Gateway
    ports:
      - '3010:3010'

  service_discovery:
    build: ./SD
    ports:
      - '4000:4000'

  order_management:
    build: ./Orders
    ports:
      - '4040:4040'

  product_catalog:
    build: ./Catalog
    ports:
      - '3030:3030'

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus

volumes:
  grafana_data: