version: '3'

services:
  gateway:
    build: ./Gateway
    ports:
      - '3010:3010'

  service_discovery:
    build: ./SD
    ports:
      - '4000:4000'

  order_management:
    build: ./Orders
    ports:
      - '4040:4040'

  product_catalog:
    build: ./Catalog
    ports:
      - '3030:3030'

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus

volumes:
  grafana_data: