version: '3'

services:
  gateway:
    build: ./Gateway
    ports:
      - '3000:3000'

  service_discovery:
    build: ./SD
    ports:
      - '4000:4000'

  order_management:
    build: ./Orders
    ports:
      - '4040:4040'

  product_catalog:
    build: ./Catalog
    ports:
      - '3030:3030'

  prometheus: 
    image: prom/prometheus:latest 
    volumes: 
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports: 
      - "19090:9090"
  
  grafana: 
    image: grafana/grafana-oss:9.4.3
    ports: 
      - "13000:3000"
    volumes: 
      - grafana-data:/var/lib/grafana
